// <auto-generated />
using System;
using EventsApi.Demo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MinimalEventsAPI.Migrations
{
    [DbContext(typeof(MinimalEventsDbContext))]
    partial class MinimalEventsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("MinimalEventsAPI.Database.MinimalEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventContact")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MinimalEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 22m,
                            Description = "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",
                            EventCode = "EVTid1",
                            EventContact = "glehon0@delicious.com",
                            EventDate = new DateTime(2022, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Bebandem",
                            Name = "elementum in hac habitasse platea dictumst morbi vestibulum velit id"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 88m,
                            Description = "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
                            EventCode = "EVTPL2",
                            EventContact = "wlendon1@odnoklassniki.ru",
                            EventDate = new DateTime(2022, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Iłowo -Osada",
                            Name = "sapien sapien non mi integer ac neque"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 26m,
                            Description = "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.",
                            EventCode = "EVTSE3",
                            EventContact = "cgorvette2@spotify.com",
                            EventDate = new DateTime(2022, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Stockholm",
                            Name = "orci pede venenatis non sodales sed tincidunt eu"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 40m,
                            Description = "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
                            EventCode = "EVTRU4",
                            EventContact = "msommerly3@godaddy.com",
                            EventDate = new DateTime(2022, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Gorshechnoye",
                            Name = "habitasse platea dictumst maecenas ut"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 35m,
                            Description = "Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
                            EventCode = "EVTCN5",
                            EventContact = "nivkovic4@psu.edu",
                            EventDate = new DateTime(2023, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Yanghuxiang",
                            Name = "donec pharetra magna vestibulum aliquet ultrices"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 29m,
                            Description = "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
                            EventCode = "EVTCN6",
                            EventContact = "gcooch5@list-manage.com",
                            EventDate = new DateTime(2022, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Chakou",
                            Name = "in hac habitasse platea dictumst morbi vestibulum velit id pretium"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 80m,
                            Description = "Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.",
                            EventCode = "EVTid7",
                            EventContact = "bcumbridge6@phpbb.com",
                            EventDate = new DateTime(2023, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Padangguci",
                            Name = "ante vestibulum ante ipsum primis in faucibus"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 10m,
                            Description = "Pellentesque at nulla. Suspendisse potenti.",
                            EventCode = "EVTCA8",
                            EventContact = "kbleackley7@scientificamerican.com",
                            EventDate = new DateTime(2023, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Saint-André-Avellin",
                            Name = "iaculis justo in hac habitasse platea dictumst etiam faucibus"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 99m,
                            Description = "Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
                            EventCode = "EVTCN9",
                            EventContact = "dberdale8@nba.com",
                            EventDate = new DateTime(2022, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Youdian",
                            Name = "eget semper rutrum nulla nunc purus phasellus in felis"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 50m,
                            Description = "Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.",
                            EventCode = "EVTCN10",
                            EventContact = "beite9@wix.com",
                            EventDate = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Zhijin",
                            Name = "pede ac diam cras pellentesque volutpat dui maecenas"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 99m,
                            Description = "Aliquam erat volutpat. In congue.",
                            EventCode = "EVTPH11",
                            EventContact = "sberreclotha@skype.com",
                            EventDate = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Tococ East",
                            Name = "mattis nibh ligula nec sem duis aliquam"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 54m,
                            Description = "Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
                            EventCode = "EVTSI12",
                            EventContact = "tcumberb@smugmug.com",
                            EventDate = new DateTime(2022, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Šentilj v Slov. Goricah",
                            Name = "tortor duis mattis egestas metus"
                        },
                        new
                        {
                            Id = 13,
                            Cost = 88m,
                            Description = "Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
                            EventCode = "EVTFR13",
                            EventContact = "cpeltzc@salon.com",
                            EventDate = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Paris 08",
                            Name = "interdum eu tincidunt in leo maecenas"
                        },
                        new
                        {
                            Id = 14,
                            Cost = 52m,
                            Description = "Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
                            EventCode = "EVTid14",
                            EventContact = "aayrisd@ezinearticles.com",
                            EventDate = new DateTime(2022, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cikupa",
                            Name = "magna ac consequat metus sapien ut"
                        },
                        new
                        {
                            Id = 15,
                            Cost = 50m,
                            Description = "Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
                            EventCode = "EVTCN15",
                            EventContact = "ffeyee@irs.gov",
                            EventDate = new DateTime(2022, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Jiaoxie",
                            Name = "luctus tincidunt nulla mollis molestie lorem"
                        },
                        new
                        {
                            Id = 16,
                            Cost = 9m,
                            Description = "Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
                            EventCode = "EVTCL16",
                            EventContact = "rhawfordf@de.vu",
                            EventDate = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Antofagasta",
                            Name = "tincidunt in leo maecenas pulvinar lobortis est"
                        },
                        new
                        {
                            Id = 17,
                            Cost = 5m,
                            Description = "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.",
                            EventCode = "EVTNG17",
                            EventContact = "jscammondeng@ezinearticles.com",
                            EventDate = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pategi",
                            Name = "faucibus accumsan odio curabitur convallis duis consequat dui nec nisi"
                        },
                        new
                        {
                            Id = 18,
                            Cost = 55m,
                            Description = "Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.",
                            EventCode = "EVTCN18",
                            EventContact = "tjancyh@mysql.com",
                            EventDate = new DateTime(2022, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Qiaozhuang",
                            Name = "lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar"
                        },
                        new
                        {
                            Id = 19,
                            Cost = 18m,
                            Description = "Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.",
                            EventCode = "EVTAR19",
                            EventContact = "edumphriesi@cisco.com",
                            EventDate = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Macachín",
                            Name = "ac enim in tempor turpis nec euismod scelerisque"
                        },
                        new
                        {
                            Id = 20,
                            Cost = 6m,
                            Description = "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
                            EventCode = "EVTSE20",
                            EventContact = "lhadfieldj@nba.com",
                            EventDate = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Kista",
                            Name = "condimentum id luctus nec molestie sed justo pellentesque viverra"
                        },
                        new
                        {
                            Id = 21,
                            Cost = 83m,
                            Description = "Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.",
                            EventCode = "EVTCN21",
                            EventContact = "gthackhamk@fema.gov",
                            EventDate = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Lianhe",
                            Name = "dis parturient montes nascetur ridiculus mus vivamus"
                        },
                        new
                        {
                            Id = 22,
                            Cost = 69m,
                            Description = "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.",
                            EventCode = "EVTPH22",
                            EventContact = "knalderl@jigsy.com",
                            EventDate = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Santa Barbara",
                            Name = "dignissim vestibulum vestibulum ante ipsum primis in"
                        },
                        new
                        {
                            Id = 23,
                            Cost = 79m,
                            Description = "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.",
                            EventCode = "EVTid23",
                            EventContact = "hhedaum@studiopress.com",
                            EventDate = new DateTime(2022, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Tutup",
                            Name = "vestibulum velit id pretium iaculis diam erat"
                        },
                        new
                        {
                            Id = 24,
                            Cost = 8m,
                            Description = "Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
                            EventCode = "EVTCN24",
                            EventContact = "pvoddenn@ucsd.edu",
                            EventDate = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Haimen",
                            Name = "ut odio cras mi pede malesuada in imperdiet et"
                        },
                        new
                        {
                            Id = 25,
                            Cost = 21m,
                            Description = "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.",
                            EventCode = "EVTAL25",
                            EventContact = "cjocelyno@reverbnation.com",
                            EventDate = new DateTime(2022, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pirg",
                            Name = "eu orci mauris lacinia sapien"
                        },
                        new
                        {
                            Id = 26,
                            Cost = 30m,
                            Description = "Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.",
                            EventCode = "EVTUA26",
                            EventContact = "dfilipp@harvard.edu",
                            EventDate = new DateTime(2022, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pokotylivka",
                            Name = "consectetuer adipiscing elit proin risus praesent lectus vestibulum quam"
                        },
                        new
                        {
                            Id = 27,
                            Cost = 72m,
                            Description = "Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.",
                            EventCode = "EVTPE27",
                            EventContact = "krossonq@pcworld.com",
                            EventDate = new DateTime(2022, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Buenos Aires",
                            Name = "molestie lorem quisque ut erat curabitur gravida nisi at nibh"
                        },
                        new
                        {
                            Id = 28,
                            Cost = 67m,
                            Description = "Duis bibendum. Morbi non quam nec dui luctus rutrum.",
                            EventCode = "EVTGH28",
                            EventContact = "hbowsr@reddit.com",
                            EventDate = new DateTime(2022, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mampong",
                            Name = "faucibus cursus urna ut tellus nulla ut erat id"
                        },
                        new
                        {
                            Id = 29,
                            Cost = 77m,
                            Description = "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
                            EventCode = "EVTCN29",
                            EventContact = "nwalcots@mysql.com",
                            EventDate = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Daguo",
                            Name = "sed augue aliquam erat volutpat in congue"
                        },
                        new
                        {
                            Id = 30,
                            Cost = 57m,
                            Description = "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.",
                            EventCode = "EVTPH30",
                            EventContact = "ckarlikt@51.la",
                            EventDate = new DateTime(2022, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Lopez Jaena",
                            Name = "eget orci vehicula condimentum curabitur in libero ut massa volutpat"
                        },
                        new
                        {
                            Id = 31,
                            Cost = 93m,
                            Description = "In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.",
                            EventCode = "EVTCU31",
                            EventContact = "sarrighettiu@cpanel.net",
                            EventDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Sagua de Tánamo",
                            Name = "non ligula pellentesque ultrices phasellus id sapien"
                        },
                        new
                        {
                            Id = 32,
                            Cost = 69m,
                            Description = "Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
                            EventCode = "EVTid32",
                            EventContact = "rhyltonv@cnn.com",
                            EventDate = new DateTime(2022, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Karangjaladri",
                            Name = "justo maecenas rhoncus aliquam lacus morbi quis tortor"
                        },
                        new
                        {
                            Id = 33,
                            Cost = 91m,
                            Description = "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.",
                            EventCode = "EVTid33",
                            EventContact = "dhechlinw@paypal.com",
                            EventDate = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Badong",
                            Name = "suspendisse potenti nullam porttitor lacus"
                        },
                        new
                        {
                            Id = 34,
                            Cost = 10m,
                            Description = "Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
                            EventCode = "EVTCN34",
                            EventContact = "baingerx@de.vu",
                            EventDate = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Guanqiao",
                            Name = "cursus vestibulum proin eu mi nulla ac"
                        },
                        new
                        {
                            Id = 35,
                            Cost = 27m,
                            Description = "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.",
                            EventCode = "EVTAZ35",
                            EventContact = "sgrannelly@nih.gov",
                            EventDate = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Beylagan",
                            Name = "magnis dis parturient montes nascetur ridiculus mus vivamus"
                        },
                        new
                        {
                            Id = 36,
                            Cost = 30m,
                            Description = "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
                            EventCode = "EVTCN36",
                            EventContact = "gbastiez@howstuffworks.com",
                            EventDate = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Tianxin",
                            Name = "consequat morbi a ipsum integer a nibh in quis"
                        },
                        new
                        {
                            Id = 37,
                            Cost = 62m,
                            Description = "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
                            EventCode = "EVTPK37",
                            EventContact = "rluquet10@sciencedaily.com",
                            EventDate = new DateTime(2022, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Nowshera Cantonment",
                            Name = "et magnis dis parturient montes nascetur ridiculus"
                        },
                        new
                        {
                            Id = 38,
                            Cost = 8m,
                            Description = "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
                            EventCode = "EVTZA38",
                            EventContact = "blebreton11@mayoclinic.com",
                            EventDate = new DateTime(2022, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Margate",
                            Name = "sed interdum venenatis turpis enim blandit mi"
                        },
                        new
                        {
                            Id = 39,
                            Cost = 83m,
                            Description = "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
                            EventCode = "EVTSE39",
                            EventContact = "achaffin12@typepad.com",
                            EventDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Umeå",
                            Name = "erat id mauris vulputate elementum nullam varius nulla facilisi cras"
                        },
                        new
                        {
                            Id = 40,
                            Cost = 75m,
                            Description = "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
                            EventCode = "EVTNC40",
                            EventContact = "fcarpmile13@1und1.de",
                            EventDate = new DateTime(2022, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Koumac",
                            Name = "cum sociis natoque penatibus et"
                        },
                        new
                        {
                            Id = 41,
                            Cost = 5m,
                            Description = "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
                            EventCode = "EVTCZ41",
                            EventContact = "mbaseke14@infoseek.co.jp",
                            EventDate = new DateTime(2022, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hostomice",
                            Name = "nunc commodo placerat praesent blandit"
                        },
                        new
                        {
                            Id = 42,
                            Cost = 42m,
                            Description = "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
                            EventCode = "EVTCN42",
                            EventContact = "bstorie15@studiopress.com",
                            EventDate = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Beishidian",
                            Name = "tortor sollicitudin mi sit amet lobortis sapien"
                        },
                        new
                        {
                            Id = 43,
                            Cost = 17m,
                            Description = "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
                            EventCode = "EVTFI43",
                            EventContact = "atresler16@instagram.com",
                            EventDate = new DateTime(2023, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Teuva",
                            Name = "cursus urna ut tellus nulla ut erat"
                        },
                        new
                        {
                            Id = 44,
                            Cost = 32m,
                            Description = "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.",
                            EventCode = "EVTRU44",
                            EventContact = "lwarmisham17@newyorker.com",
                            EventDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Krasnyy Yar",
                            Name = "integer aliquet massa id lobortis convallis tortor risus dapibus augue"
                        },
                        new
                        {
                            Id = 45,
                            Cost = 76m,
                            Description = "Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
                            EventCode = "EVTPE45",
                            EventContact = "mdomenc18@joomla.org",
                            EventDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Asquipata",
                            Name = "molestie sed justo pellentesque viverra pede"
                        },
                        new
                        {
                            Id = 46,
                            Cost = 65m,
                            Description = "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
                            EventCode = "EVTid46",
                            EventContact = "cdifrancesco19@tamu.edu",
                            EventDate = new DateTime(2022, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Wadeng",
                            Name = "molestie sed justo pellentesque viverra pede ac diam cras"
                        },
                        new
                        {
                            Id = 47,
                            Cost = 34m,
                            Description = "Morbi a ipsum. Integer a nibh.",
                            EventCode = "EVTCN47",
                            EventContact = "tstanney1a@omniture.com",
                            EventDate = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Gao’an",
                            Name = "vestibulum ac est lacinia nisi venenatis tristique fusce"
                        },
                        new
                        {
                            Id = 48,
                            Cost = 52m,
                            Description = "In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
                            EventCode = "EVTCN48",
                            EventContact = "rbarabisch1b@istockphoto.com",
                            EventDate = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Zongzhai",
                            Name = "donec quis orci eget orci vehicula condimentum curabitur in"
                        },
                        new
                        {
                            Id = 49,
                            Cost = 92m,
                            Description = "Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
                            EventCode = "EVTUG49",
                            EventContact = "bhodjetts1c@sourceforge.net",
                            EventDate = new DateTime(2022, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Nyachera",
                            Name = "ut suscipit a feugiat et eros vestibulum ac est lacinia"
                        },
                        new
                        {
                            Id = 50,
                            Cost = 1m,
                            Description = "Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.",
                            EventCode = "EVTSE50",
                            EventContact = "bmedlin1d@google.de",
                            EventDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Vännäs",
                            Name = "vestibulum ac est lacinia nisi venenatis"
                        },
                        new
                        {
                            Id = 51,
                            Cost = 11m,
                            Description = "Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
                            EventCode = "EVTCA51",
                            EventContact = "vsheivels1e@hud.gov",
                            EventDate = new DateTime(2023, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Coaldale",
                            Name = "diam erat fermentum justo nec condimentum neque sapien placerat"
                        },
                        new
                        {
                            Id = 52,
                            Cost = 62m,
                            Description = "Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
                            EventCode = "EVTCN52",
                            EventContact = "bpass1f@hugedomains.com",
                            EventDate = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Jinzhou",
                            Name = "in felis donec semper sapien"
                        },
                        new
                        {
                            Id = 53,
                            Cost = 28m,
                            Description = "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.",
                            EventCode = "EVTSA53",
                            EventContact = "sdetheridge1g@gnu.org",
                            EventDate = new DateTime(2022, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Al Khafjī",
                            Name = "rutrum neque aenean auctor gravida sem praesent id massa"
                        },
                        new
                        {
                            Id = 54,
                            Cost = 23m,
                            Description = "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
                            EventCode = "EVTNC54",
                            EventContact = "psuffield1h@telegraph.co.uk",
                            EventDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Tadine",
                            Name = "nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum"
                        },
                        new
                        {
                            Id = 55,
                            Cost = 24m,
                            Description = "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
                            EventCode = "EVTPL55",
                            EventContact = "griccardini1i@virginia.edu",
                            EventDate = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Śródmieście",
                            Name = "tincidunt eu felis fusce posuere"
                        },
                        new
                        {
                            Id = 56,
                            Cost = 4m,
                            Description = "Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.",
                            EventCode = "EVTBR56",
                            EventContact = "mlomis1j@google.com",
                            EventDate = new DateTime(2022, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "São Gonçalo do Sapucaí",
                            Name = "dolor sit amet consectetuer adipiscing"
                        },
                        new
                        {
                            Id = 57,
                            Cost = 75m,
                            Description = "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
                            EventCode = "EVTPH57",
                            EventContact = "mavrahamov1k@state.tx.us",
                            EventDate = new DateTime(2022, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Paniqui",
                            Name = "vivamus vestibulum sagittis sapien cum sociis natoque penatibus et"
                        },
                        new
                        {
                            Id = 58,
                            Cost = 18m,
                            Description = "Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.",
                            EventCode = "EVTPT58",
                            EventContact = "lblinerman1l@addtoany.com",
                            EventDate = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Rio Covo ( Santa Eulália )",
                            Name = "aliquam quis turpis eget elit sodales scelerisque"
                        },
                        new
                        {
                            Id = 59,
                            Cost = 98m,
                            Description = "Phasellus sit amet erat. Nulla tempus.",
                            EventCode = "EVTSE59",
                            EventContact = "gwebermann1m@istockphoto.com",
                            EventDate = new DateTime(2022, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Stockholm",
                            Name = "at diam nam tristique tortor"
                        },
                        new
                        {
                            Id = 60,
                            Cost = 75m,
                            Description = "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
                            EventCode = "EVTFI60",
                            EventContact = "btorrisi1n@youtube.com",
                            EventDate = new DateTime(2022, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Turku",
                            Name = "semper interdum mauris ullamcorper purus sit amet nulla quisque"
                        },
                        new
                        {
                            Id = 61,
                            Cost = 22m,
                            Description = "Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.",
                            EventCode = "EVTFI61",
                            EventContact = "anewstead1o@sogou.com",
                            EventDate = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Kuhmoinen",
                            Name = "at velit vivamus vel nulla eget eros elementum pellentesque quisque"
                        },
                        new
                        {
                            Id = 62,
                            Cost = 78m,
                            Description = "Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.",
                            EventCode = "EVTMA62",
                            EventContact = "hschober1p@accuweather.com",
                            EventDate = new DateTime(2022, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Touama",
                            Name = "id consequat in consequat ut nulla sed accumsan felis ut"
                        },
                        new
                        {
                            Id = 63,
                            Cost = 91m,
                            Description = "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
                            EventCode = "EVTMX63",
                            EventContact = "csowood1q@mayoclinic.com",
                            EventDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Providencia",
                            Name = "quam sollicitudin vitae consectetuer eget rutrum at lorem"
                        },
                        new
                        {
                            Id = 64,
                            Cost = 35m,
                            Description = "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
                            EventCode = "EVTPH64",
                            EventContact = "ggabbott1r@yolasite.com",
                            EventDate = new DateTime(2022, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "San Francisco",
                            Name = "leo rhoncus sed vestibulum sit"
                        },
                        new
                        {
                            Id = 65,
                            Cost = 46m,
                            Description = "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
                            EventCode = "EVTPS65",
                            EventContact = "khamm1s@chronoengine.com",
                            EventDate = new DateTime(2022, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Dayr Sāmit",
                            Name = "mauris enim leo rhoncus sed vestibulum sit"
                        },
                        new
                        {
                            Id = 66,
                            Cost = 93m,
                            Description = "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.",
                            EventCode = "EVTNO66",
                            EventContact = "apaolacci1t@surveymonkey.com",
                            EventDate = new DateTime(2022, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Oslo",
                            Name = "vestibulum rutrum rutrum neque aenean"
                        },
                        new
                        {
                            Id = 67,
                            Cost = 83m,
                            Description = "In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.",
                            EventCode = "EVTSE67",
                            EventContact = "gpoure1u@symantec.com",
                            EventDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Kungsbacka",
                            Name = "purus eu magna vulputate luctus"
                        },
                        new
                        {
                            Id = 68,
                            Cost = 34m,
                            Description = "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
                            EventCode = "EVTFR68",
                            EventContact = "apigden1v@hubpages.com",
                            EventDate = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Paris 13",
                            Name = "metus arcu adipiscing molestie hendrerit at"
                        },
                        new
                        {
                            Id = 69,
                            Cost = 4m,
                            Description = "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.",
                            EventCode = "EVTid69",
                            EventContact = "nsurgood1w@cbc.ca",
                            EventDate = new DateTime(2022, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Sasar",
                            Name = "nulla suspendisse potenti cras in purus eu magna vulputate luctus"
                        },
                        new
                        {
                            Id = 70,
                            Cost = 9m,
                            Description = "Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
                            EventCode = "EVTCN70",
                            EventContact = "mscahill1x@surveymonkey.com",
                            EventDate = new DateTime(2022, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Huarong",
                            Name = "ac diam cras pellentesque volutpat dui maecenas tristique est et"
                        },
                        new
                        {
                            Id = 71,
                            Cost = 48m,
                            Description = "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.",
                            EventCode = "EVTKM71",
                            EventContact = "ngokes1y@amazon.de",
                            EventDate = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hoani",
                            Name = "nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel"
                        },
                        new
                        {
                            Id = 72,
                            Cost = 12m,
                            Description = "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.",
                            EventCode = "EVTVE72",
                            EventContact = "rockleshaw1z@studiopress.com",
                            EventDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Guacara",
                            Name = "amet nulla quisque arcu libero rutrum ac lobortis"
                        },
                        new
                        {
                            Id = 73,
                            Cost = 100m,
                            Description = "Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.",
                            EventCode = "EVTCO73",
                            EventContact = "acarnier20@jalbum.net",
                            EventDate = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "El Copey",
                            Name = "at turpis a pede posuere"
                        },
                        new
                        {
                            Id = 74,
                            Cost = 80m,
                            Description = "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.",
                            EventCode = "EVTCN74",
                            EventContact = "rwallace21@booking.com",
                            EventDate = new DateTime(2022, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Huangqiang",
                            Name = "eget orci vehicula condimentum curabitur in libero ut"
                        },
                        new
                        {
                            Id = 75,
                            Cost = 40m,
                            Description = "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
                            EventCode = "EVTid75",
                            EventContact = "mmaling22@bigcartel.com",
                            EventDate = new DateTime(2022, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pendolo",
                            Name = "erat fermentum justo nec condimentum neque sapien"
                        },
                        new
                        {
                            Id = 76,
                            Cost = 82m,
                            Description = "In congue. Etiam justo. Etiam pretium iaculis justo.",
                            EventCode = "EVTCN76",
                            EventContact = "barmatidge23@samsung.com",
                            EventDate = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hetang",
                            Name = "ullamcorper augue a suscipit nulla elit ac nulla"
                        },
                        new
                        {
                            Id = 77,
                            Cost = 74m,
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
                            EventCode = "EVTCN77",
                            EventContact = "mjess24@pcworld.com",
                            EventDate = new DateTime(2022, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Xinglong",
                            Name = "a odio in hac habitasse platea dictumst maecenas"
                        },
                        new
                        {
                            Id = 78,
                            Cost = 75m,
                            Description = "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.",
                            EventCode = "EVTHN78",
                            EventContact = "cfinder25@cargocollective.com",
                            EventDate = new DateTime(2022, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "El Porvenir",
                            Name = "libero ut massa volutpat convallis morbi odio odio"
                        },
                        new
                        {
                            Id = 79,
                            Cost = 23m,
                            Description = "Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.",
                            EventCode = "EVTCN79",
                            EventContact = "abullingham26@fc2.com",
                            EventDate = new DateTime(2022, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Puzi",
                            Name = "consequat nulla nisl nunc nisl duis bibendum"
                        },
                        new
                        {
                            Id = 80,
                            Cost = 41m,
                            Description = "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.",
                            EventCode = "EVTBR80",
                            EventContact = "tticksall27@dmoz.org",
                            EventDate = new DateTime(2022, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Afogados da Ingazeira",
                            Name = "amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque"
                        },
                        new
                        {
                            Id = 81,
                            Cost = 6m,
                            Description = "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",
                            EventCode = "EVTET81",
                            EventContact = "dmacourek28@angelfire.com",
                            EventDate = new DateTime(2022, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Addiet Canna",
                            Name = "et ultrices posuere cubilia curae nulla dapibus dolor vel"
                        },
                        new
                        {
                            Id = 82,
                            Cost = 19m,
                            Description = "Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
                            EventCode = "EVTid82",
                            EventContact = "notierney29@godaddy.com",
                            EventDate = new DateTime(2022, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Desa Baregbeg",
                            Name = "etiam justo etiam pretium iaculis"
                        },
                        new
                        {
                            Id = 83,
                            Cost = 68m,
                            Description = "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
                            EventCode = "EVTPY83",
                            EventContact = "kbellas2a@edublogs.org",
                            EventDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "San Pedro del Paraná",
                            Name = "ipsum integer a nibh in quis justo maecenas"
                        },
                        new
                        {
                            Id = 84,
                            Cost = 20m,
                            Description = "In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.",
                            EventCode = "EVTCN84",
                            EventContact = "mwilkie2b@zdnet.com",
                            EventDate = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Xuetian",
                            Name = "ipsum primis in faucibus orci luctus et ultrices posuere"
                        },
                        new
                        {
                            Id = 85,
                            Cost = 39m,
                            Description = "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
                            EventCode = "EVTMK85",
                            EventContact = "amcleary2c@shutterfly.com",
                            EventDate = new DateTime(2022, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Крива Паланка",
                            Name = "nunc viverra dapibus nulla suscipit ligula in lacus"
                        },
                        new
                        {
                            Id = 86,
                            Cost = 47m,
                            Description = "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.",
                            EventCode = "EVTJO86",
                            EventContact = "dallderidge2d@skyrock.com",
                            EventDate = new DateTime(2022, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Ash Shajarah",
                            Name = "vulputate vitae nisl aenean lectus pellentesque eget nunc"
                        },
                        new
                        {
                            Id = 87,
                            Cost = 20m,
                            Description = "Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.",
                            EventCode = "EVTRU87",
                            EventContact = "mmarrow2e@yandex.ru",
                            EventDate = new DateTime(2022, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Starokorsunskaya",
                            Name = "quis turpis sed ante vivamus tortor duis"
                        },
                        new
                        {
                            Id = 88,
                            Cost = 42m,
                            Description = "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.",
                            EventCode = "EVTCN88",
                            EventContact = "glinck2f@guardian.co.uk",
                            EventDate = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Tawen Aobao",
                            Name = "quam sollicitudin vitae consectetuer eget"
                        },
                        new
                        {
                            Id = 89,
                            Cost = 41m,
                            Description = "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.",
                            EventCode = "EVTZA89",
                            EventContact = "mhuey2g@dailymail.co.uk",
                            EventDate = new DateTime(2022, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Duiwelskloof",
                            Name = "libero rutrum ac lobortis vel dapibus"
                        },
                        new
                        {
                            Id = 90,
                            Cost = 45m,
                            Description = "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.",
                            EventCode = "EVTRU90",
                            EventContact = "miveagh2h@engadget.com",
                            EventDate = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Krasnovishersk",
                            Name = "justo in blandit ultrices enim lorem ipsum"
                        },
                        new
                        {
                            Id = 91,
                            Cost = 30m,
                            Description = "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.",
                            EventCode = "EVTUS91",
                            EventContact = "gkesteven2i@bing.com",
                            EventDate = new DateTime(2023, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Houston",
                            Name = "leo pellentesque ultrices mattis odio"
                        },
                        new
                        {
                            Id = 92,
                            Cost = 37m,
                            Description = "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
                            EventCode = "EVTBR92",
                            EventContact = "amckea2j@fema.gov",
                            EventDate = new DateTime(2022, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Maragogi",
                            Name = "sed justo pellentesque viverra pede ac diam"
                        },
                        new
                        {
                            Id = 93,
                            Cost = 89m,
                            Description = "Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.",
                            EventCode = "EVTPE93",
                            EventContact = "bdewitt2k@sun.com",
                            EventDate = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pacasmayo",
                            Name = "vitae mattis nibh ligula nec sem"
                        },
                        new
                        {
                            Id = 94,
                            Cost = 38m,
                            Description = "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
                            EventCode = "EVTLU94",
                            EventContact = "mbeecheno2l@ftc.gov",
                            EventDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Clervaux",
                            Name = "amet cursus id turpis integer aliquet massa id"
                        },
                        new
                        {
                            Id = 95,
                            Cost = 75m,
                            Description = "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
                            EventCode = "EVTPH95",
                            EventContact = "fnijs2m@home.pl",
                            EventDate = new DateTime(2022, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cayungnan",
                            Name = "aliquam augue quam sollicitudin vitae consectetuer eget"
                        },
                        new
                        {
                            Id = 96,
                            Cost = 14m,
                            Description = "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.",
                            EventCode = "EVTMN96",
                            EventContact = "hmcpeake2n@guardian.co.uk",
                            EventDate = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Sharïngol",
                            Name = "urna pretium nisl ut volutpat sapien"
                        },
                        new
                        {
                            Id = 97,
                            Cost = 38m,
                            Description = "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
                            EventCode = "EVTRU97",
                            EventContact = "caspey2o@dedecms.com",
                            EventDate = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Dvinskoy",
                            Name = "bibendum morbi non quam nec"
                        },
                        new
                        {
                            Id = 98,
                            Cost = 46m,
                            Description = "Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.",
                            EventCode = "EVTCN98",
                            EventContact = "fperceval2p@mediafire.com",
                            EventDate = new DateTime(2022, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Dayou",
                            Name = "congue risus semper porta volutpat quam pede lobortis ligula sit"
                        },
                        new
                        {
                            Id = 99,
                            Cost = 30m,
                            Description = "Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.",
                            EventCode = "EVTGR99",
                            EventContact = "bpostance2q@google.com.br",
                            EventDate = new DateTime(2022, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Plátanos",
                            Name = "sit amet erat nulla tempus"
                        },
                        new
                        {
                            Id = 100,
                            Cost = 68m,
                            Description = "Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
                            EventCode = "EVTid100",
                            EventContact = "lmcgeoch2r@g.co",
                            EventDate = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Panenggoede",
                            Name = "et magnis dis parturient montes nascetur ridiculus mus vivamus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
